server:
  port: 8889

spring:
  application:
    name: discovery-service
  security:
    user:
      name: discovery-client
      password: ak$Au1bS8

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/